# Multilingual configuration

defaultContentLanguage = "en"

[languages.en]
languageName = "English"
contentDir = "content/en"
weight = 10


[languages.ru]
languageName = "Russian"
contentDir = "content/ru"
weight = 20
