# Multilingual configuration

defaultContentLanguage = "en"

[languages.en]
languageName = "English"
contentDir = "content/comparison/en"
weight = 10

[languages.de]
languageName = "German"
contentDir = "content/comparison/de"
weight = 20

[languages.ru]
languageName = "Russian"
contentDir = "content/comparison/ru"
weight = 30

[languages.zh]
languageName = "Chenise"
contentDir = "content/comparison/ru"
weight = 40
