name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:
    branches:    
      - multilanguage
  # Run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      PRODUCT: comparison

    steps:
      - uses: actions/checkout@v2

      - name: Submodule update
        run: |
          git submodule update --init --recursive
          git submodule foreach git pull origin master

      - name: Install Hugo
        run: |
          curl -LO https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_extended_0.101.0_Linux-64bit.deb
          sudo dpkg -i hugo_extended_0.101.0_Linux-64bit.deb
          
      - name: Run and build Hugo
        run: |
          mkdir -p common/content/en
          mkdir -p common/content/ru
          cp -r en common/content/en
          cp -r ru common/content/ru
          cp multilanguage-config.toml common
          hugo --source common --minify --config config-geekdoc.toml,ignore-total-config.toml,show-feedback-config.toml,multilanguage-config.toml
